language: elm

node_js: '12'

sudo: required
dist: trusty

elm:
  - latest
elm_test: latest
elm_format: latest

cache:
  yarn: true
  directories:
    - node_modules
    - elm_cache_linux
    - elm_cache_osx

env:
  - GAME_SOUNDS="" NODE_ENV=production GAME=Tiled GAME_URL="https://math.z0.lv/"

#os:
#  - linux
#  - osx

before_install:
  #Elm cache folders for each OS
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export ELM_HOME=./elm_cache_linux; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export ELM_HOME=./elm_cache_osx; fi


#before_script:
#  - elm-format --validate . && elm-test #&& elm-test lib/elm-tiled && elm-test lib/elm-image

script:
  - cd benchmark
  - elm make src/Main.elm --output=./gh-pages/bundle.js
  - elm make src/Main.elm --optimize --output=./gh-pages/bundle.optimize.js
  - elm make src/Main.elm --optimize --output=./benchmark/gh-pages/bundle.min.js
  - cd ..
  - jscodeshift -t transform.js ./benchmark/gh-pages/bundle.min.js
  - uglifyjs ./benchmark/gh-pages/bundle.min.js --compress "pure_funcs=[F2,F3,F4,F5,F6,F7,F8,F9,A2,A3,A4,A5,A6,A7,A8,A9],pure_getters" --output=./benchmark/gh-pages/bundle.min.js
  - prepack ./benchmark/gh-pages/bundle.min.js --inlineExpressions --out ./benchmark/gh-pages/bundle.min.js
  - terser ./benchmark/gh-pages/bundle.min.js ./gh-pages/script.js --compress 'keep_fargs=false,unsafe_comps,unsafe' --mangle --output=./benchmark/gh-pages/bundle.min.js
  - posthtml ./gh-pages/index.html -o ./gh-pages/index.html -c posthtml.config.js

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: benchmark/gh-pages
  on:
    branch: master
